services:
    tas2580.mobilenotifier.listener:
        class: tas2580\mobilenotifier\event\listener
        arguments:
            - @request
            - @user
            - @template
            - @service_container
            - %core.root_path%
        tags:
            - { name: event.listener }
    tas2580.mobilenotifier.src.helper:
        class: tas2580\mobilenotifier\src\helper
        arguments:
            - @config
            - @user
            - @request
            - %core.root_path%
            - %core.php_ext%
    notification.method.mobilenotifier:
        class: tas2580\mobilenotifier\notification\method\mobilenotifier
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: notification.method }